/*
 * Copyright 2022 Google LLC
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * version 2 as published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 */

// TODO this should come from Malloy directly, rather than being hard-coded here.
export const RESERVED_WORDS = [
  "accept",
  "aggregate",
  "declare",
  "dimension",
  "except",
  "explore",
  "group_by",
  "having",
  "index",
  "join_cross",
  "join_one",
  "join_many",
  "limit",
  "measure",
  "nest",
  "order_by",
  "primary_key",
  "project",
  "query",
  "rename",
  "sample",
  "source",
  "sql",
  "turduck",
  "top",
  "where",
  "all",
  "as",
  "asc",
  "avg",
  "boolean",
  "by",
  "case",
  "cast",
  "condition",
  "count",
  "date",
  "day",
  "days",
  "desc",
  "distinct",
  "else",
  "end",
  "exclude",
  "false",
  "for",
  "from",
  "from_sql",
  "has",
  "hour",
  "hours",
  "import",
  "is",
  "json",
  "last",
  "max",
  "min",
  "minute",
  "minutes",
  "month",
  "months",
  "not",
  "now",
  "null",
  "number",
  "on",
  "or",
  "pick",
  "quarter",
  "quarters",
  "second",
  "seconds",
  "string",
  "sum",
  "table",
  "then",
  "this",
  "timestamp",
  "to",
  "true",
  "turtle",
  "week",
  "weeks",
  "when",
  "with",
  "year",
  "years",
  "ungrouped",
];
